### ISSUE TITLE
DefaultFooter doesn't change copyright

### ISSUE THREAD

**Issue by ncioj10** [ant-design/ant-design-pro-layout#29]
Hi,
when I try to change the DefaultFooter copyright within in the UserLayout.tsx of my ant pro app, by using 
`<DefaultFooter copyright="xyz"  />` nothing changes. How can it be changed?

Best,
Nico

**Comment by ncioj10** [comment]
I'm working on the newest version 4.5.6

**Comment by chenshuai2144** [comment]
Lucky person, I just released a new version.

**Comment by ncioj10** [comment]
Thank you for the quick reply. Unfortunately I've already pulled the new version you created as written above. Somehow it still doesn't seem to change.

**Comment by ncioj10** [comment]
Could resolve the issue. My bad.
